name: publish-to-ansible-galaxy
on:
  release:
    types: [published]
jobs:
  update-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update version
      run: |
        echo "Updating version"
        sed -i "s/version: .*/version: ${{ github.event.release.tag_name }}/g" dominion_solutions/netbird/galaxy.yml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update version to ${{ github.event.release.tag_name }}"
        branch: "main"

  ansible-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ansible/ansible-publish-action@v1.0.0
      with:
        api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
        api_server: https://galaxy.ansible.com/api/
        src_path: /github/workspace/dominion_solutions/netbird
