name: Run Ansible Unit Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/dominion_solutions/netbird

      - name: Install dependencies
        run: |
          cd ansible_collections/dominion_solutions/netbird
          pip install -r requirements.txt

      - name: Run Ansible Unit Tests
        run: |
          cd ansible_collections/dominion_solutions/netbird
          ansible-playbook tests/unit_tests.yml
